version: '3.8'

services:
  sextant:
    build:
      context: ./sextant
    ports:
      - "3000:3000"
    volumes:
      - ./sextant:/app

  pylon:
    build:
      context: ./pylon
    ports:
      - "55455:55455"
    volumes:
      - ./pylon:/app
